version: "3.9"

services:
  mqtt_broker:
    image: eclipse-mosquitto
    container_name: mqtt_broker
    user: "root"
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mqtt_data:/mosquitto/data
      - ./mqtt_logs:/mosquitto/log
    restart: always

  postgres_db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iot_logs
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
    restart: always

  hub:
    build: ./Hub
    container_name: hub
    environment:
      - BROKER_ADDRESS=mqtt_broker
      - MQTT_USERNAME=iotuser
      - MQTT_PASSWORD=iotpassword
      - DB_HOST=postgres_db
    depends_on:
      - mqtt_broker
      - postgres_db
    command: ["python", "hub.py"]

  temperature_sensor:
    build: ./Sensors/Temperature
    container_name: sensor-temp
    environment:
      - BROKER_ADDRESS=mqtt_broker
      - MQTT_USERNAME=iotuser
      - MQTT_PASSWORD=iotpassword
    depends_on:
      - mqtt_broker
    command: ["python", "stemp.py"]

  motion_sensor:
    build: ./Sensors/Motion
    container_name: sensor-motion
    environment:
      - BROKER_ADDRESS=mqtt_broker
      - MQTT_USERNAME=iotuser
      - MQTT_PASSWORD=iotpassword
    depends_on:
      - mqtt_broker
    command: ["python", "smotion.py"]

  gas_sensor:
    build: ./Sensors/Gas
    container_name: sensor-gas
    environment:
      - BROKER_ADDRESS=mqtt_broker
      - MQTT_USERNAME=iotuser
      - MQTT_PASSWORD=iotpassword
    depends_on:
      - mqtt_broker
    command: ["python", "sgas.py"]

  ac_actuator:
    build: ./Actuators/Cooling-Heating
    container_name: HVAC
    environment:
      - BROKER_ADDRESS=mqtt_broker
      - MQTT_USERNAME=iotuser
      - MQTT_PASSWORD=iotpassword
    depends_on:
      - mqtt_broker
    command: ["python", "HVAC.py"]

  door_actuator:
    build: ./Actuators/Door
    container_name: door
    environment:
    
      - BROKER_ADDRESS=mqtt_broker
      - MQTT_USERNAME=iotuser
      - MQTT_PASSWORD=iotpassword
    depends_on:
      - mqtt_broker
    command: ["python", "Adoor.py"]

  gas_alarm:
    build: ./Actuators/Alarm
    container_name: alarm
    environment:
    
      - BROKER_ADDRESS=mqtt_broker
      - MQTT_USERNAME=iotuser
      - MQTT_PASSWORD=iotpassword
    depends_on:
      - mqtt_broker
    command: ["python", "GasActuator.py"]
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - default

  ddos_attacker:
    build:
      context: ./Attackers/DDoS
      dockerfile: Dockerfile
    container_name: ddos_attacker
    environment:
      - BROKER_ADDRESS=mqtt_broker
      - TARGET_TOPIC=building/zone3/gas/detection
      - ATTACK_RATE=0.01
    depends_on:
      - mqtt_broker
    profiles:
      - attacks
      
      
  hijack_attacker:
    build:
      context: ./Attackers/Hijack
      dockerfile: Dockerfile
    container_name: hijack_attacker
    environment:
      - BROKER_ADDRESS=mqtt_broker
      - ATTACK_INTERVAL=3
    depends_on:
      - mqtt_broker
    profiles:
      - attacks
  
  mqtt_sniffer:
    build:
      context: ./Attackers/MQTT-Sniffer
    container_name: mqtt_sniffer
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: "bridge"
    depends_on:
      - mqtt_broker
    profiles:
      - attacks


volumes:
  pgdata:
  mqtt_data:
  mqtt_logs:

